// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Project.proto

package SpringBoot.dto;

public interface EmployeeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:routeguide.Employee)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     *
     * @return The id.
     */
    int getId();

    /**
     * <code>string visa = 2;</code>
     *
     * @return The visa.
     */
    String getVisa();

    /**
     * <code>string visa = 2;</code>
     *
     * @return The bytes for visa.
     */
    com.google.protobuf.ByteString
    getVisaBytes();

    /**
     * <code>string first_name = 3;</code>
     *
     * @return The firstName.
     */
    String getFirstName();

    /**
     * <code>string first_name = 3;</code>
     *
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
    getFirstNameBytes();

    /**
     * <code>string last_name = 4;</code>
     *
     * @return The lastName.
     */
    String getLastName();

    /**
     * <code>string last_name = 4;</code>
     *
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
    getLastNameBytes();

    /**
     * <code>string birth_day = 5;</code>
     *
     * @return The birthDay.
     */
    String getBirthDay();

    /**
     * <code>string birth_day = 5;</code>
     *
     * @return The bytes for birthDay.
     */
    com.google.protobuf.ByteString
    getBirthDayBytes();

    /**
     * <code>int32 version = 6;</code>
     *
     * @return The version.
     */
    int getVersion();
}
