// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Project.proto

package SpringBoot.dto;

public interface GroupOrBuilder extends
        // @@protoc_insertion_point(interface_extends:routeguide.Group)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     *
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 group_leader_id = 2;</code>
     *
     * @return The groupLeaderId.
     */
    int getGroupLeaderId();

    /**
     * <code>int32 version = 3;</code>
     *
     * @return The version.
     */
    int getVersion();

    /**
     * <code>string name = 4;</code>
     *
     * @return The name.
     */
    String getName();

    /**
     * <code>string name = 4;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();
}
