// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Project.proto

package SpringBoot.dto;

public final class MyProto {
    private MyProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_routeguide_Project_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_routeguide_Project_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_routeguide_Response_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_routeguide_Response_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_routeguide_Request_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_routeguide_Request_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_routeguide_Employee_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_routeguide_Employee_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_routeguide_Group_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_routeguide_Group_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\rProject.proto\022\nrouteguide\"\276\001\n\007Project\022" +
                        "\n\n\002id\030\n \001(\005\022\020\n\010group_id\030\002 \001(\005\022\026\n\016project" +
                        "_number\030\003 \001(\005\022\024\n\014project_name\030\004 \001(\t\022\016\n\006m" +
                        "ember\030\001 \001(\t\022\020\n\010customer\030\005 \001(\t\022\016\n\006status\030" +
                        "\006 \001(\t\022\022\n\nstart_date\030\007 \001(\t\022\020\n\010end_date\030\010 " +
                        "\001(\t\022\017\n\007version\030\t \001(\005\"/\n\010Response\022\022\n\nis_s" +
                        "uccess\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"}\n\007Request" +
                        "\022\024\n\014type_request\030\001 \001(\005\022\014\n\004page\030\002 \001(\005\022\030\n\020" +
                        "max_item_in_page\030\003 \001(\005\022\016\n\006search\030\004 \001(\t\022$" +
                        "\n\007project\030\005 \001(\0132\023.routeguide.Project\"o\n\010" +
                        "Employee\022\n\n\002id\030\001 \001(\005\022\014\n\004visa\030\002 \001(\t\022\022\n\nfi" +
                        "rst_name\030\003 \001(\t\022\021\n\tlast_name\030\004 \001(\t\022\021\n\tbir" +
                        "th_day\030\005 \001(\t\022\017\n\007version\030\006 \001(\005\"K\n\005Group\022\n" +
                        "\n\002id\030\001 \001(\005\022\027\n\017group_leader_id\030\002 \001(\005\022\017\n\007v" +
                        "ersion\030\003 \001(\005\022\014\n\004name\030\004 \001(\t2\343\003\n\tMyService" +
                        "\0229\n\naddProject\022\023.routeguide.Project\032\024.ro" +
                        "uteguide.Response\"\000\022;\n\013getProjects\022\023.rou" +
                        "teguide.Request\032\023.routeguide.Project\"\0000\001" +
                        "\0227\n\tgetGroups\022\023.routeguide.Request\032\021.rou" +
                        "teguide.Group\"\0000\001\022<\n\rupdateProject\022\023.rou" +
                        "teguide.Project\032\024.routeguide.Response\"\000\022" +
                        "<\n\rdeleteProject\022\023.routeguide.Project\032\024." +
                        "routeguide.Response\"\000\0225\n\010addGroup\022\021.rout" +
                        "eguide.Group\032\024.routeguide.Response\"\000\0228\n\013" +
                        "updateGroup\022\021.routeguide.Group\032\024.routegu" +
                        "ide.Response\"\000\0228\n\013deleteGroup\022\021.routegui" +
                        "de.Group\032\024.routeguide.Response\"\000B!\n\016gene" +
                        "ratedclassB\007MyProtoP\001\242\002\003RTGb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_routeguide_Project_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_routeguide_Project_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_routeguide_Project_descriptor,
                new String[]{"Id", "GroupId", "ProjectNumber", "ProjectName", "Member", "Customer", "Status", "StartDate", "EndDate", "Version",});
        internal_static_routeguide_Response_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_routeguide_Response_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_routeguide_Response_descriptor,
                new String[]{"IsSuccess", "Message",});
        internal_static_routeguide_Request_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_routeguide_Request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_routeguide_Request_descriptor,
                new String[]{"TypeRequest", "Page", "MaxItemInPage", "Search", "Project",});
        internal_static_routeguide_Employee_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_routeguide_Employee_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_routeguide_Employee_descriptor,
                new String[]{"Id", "Visa", "FirstName", "LastName", "BirthDay", "Version",});
        internal_static_routeguide_Group_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_routeguide_Group_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_routeguide_Group_descriptor,
                new String[]{"Id", "GroupLeaderId", "Version", "Name",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
