// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Project.proto

package SpringBoot.dto;

public interface ProjectOrBuilder extends
        // @@protoc_insertion_point(interface_extends:routeguide.Project)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 10;</code>
     *
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 group_id = 2;</code>
     *
     * @return The groupId.
     */
    int getGroupId();

    /**
     * <code>int32 project_number = 3;</code>
     *
     * @return The projectNumber.
     */
    int getProjectNumber();

    /**
     * <code>string project_name = 4;</code>
     *
     * @return The projectName.
     */
    String getProjectName();

    /**
     * <code>string project_name = 4;</code>
     *
     * @return The bytes for projectName.
     */
    com.google.protobuf.ByteString
    getProjectNameBytes();

    /**
     * <code>string member = 1;</code>
     *
     * @return The member.
     */
    String getMember();

    /**
     * <code>string member = 1;</code>
     *
     * @return The bytes for member.
     */
    com.google.protobuf.ByteString
    getMemberBytes();

    /**
     * <code>string customer = 5;</code>
     *
     * @return The customer.
     */
    String getCustomer();

    /**
     * <code>string customer = 5;</code>
     *
     * @return The bytes for customer.
     */
    com.google.protobuf.ByteString
    getCustomerBytes();

    /**
     * <code>string status = 6;</code>
     *
     * @return The status.
     */
    String getStatus();

    /**
     * <code>string status = 6;</code>
     *
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
    getStatusBytes();

    /**
     * <code>string start_date = 7;</code>
     *
     * @return The startDate.
     */
    String getStartDate();

    /**
     * <code>string start_date = 7;</code>
     *
     * @return The bytes for startDate.
     */
    com.google.protobuf.ByteString
    getStartDateBytes();

    /**
     * <code>string end_date = 8;</code>
     *
     * @return The endDate.
     */
    String getEndDate();

    /**
     * <code>string end_date = 8;</code>
     *
     * @return The bytes for endDate.
     */
    com.google.protobuf.ByteString
    getEndDateBytes();

    /**
     * <code>int32 version = 9;</code>
     *
     * @return The version.
     */
    int getVersion();
}
