// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Project.proto

package SpringBoot.dto;

/**
 * <pre>
 * </pre>
 * <p>
 * Protobuf type {@code routeguide.Project}
 */
public final class Project extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:routeguide.Project)
        ProjectOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Project.newBuilder() to construct.
    private Project(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Project() {
        projectName_ = "";
        member_ = "";
        customer_ = "";
        status_ = "";
        startDate_ = "";
        endDate_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new Project();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private Project(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        member_ = s;
                        break;
                    }
                    case 16: {

                        groupId_ = input.readInt32();
                        break;
                    }
                    case 24: {

                        projectNumber_ = input.readInt32();
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        projectName_ = s;
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        customer_ = s;
                        break;
                    }
                    case 50: {
                        String s = input.readStringRequireUtf8();

                        status_ = s;
                        break;
                    }
                    case 58: {
                        String s = input.readStringRequireUtf8();

                        startDate_ = s;
                        break;
                    }
                    case 66: {
                        String s = input.readStringRequireUtf8();

                        endDate_ = s;
                        break;
                    }
                    case 72: {

                        version_ = input.readInt32();
                        break;
                    }
                    case 80: {

                        id_ = input.readInt32();
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return MyProto.internal_static_routeguide_Project_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return MyProto.internal_static_routeguide_Project_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Project.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 10;
    private int id_;

    /**
     * <code>int32 id = 10;</code>
     *
     * @return The id.
     */
    public int getId() {
        return id_;
    }

    public static final int GROUP_ID_FIELD_NUMBER = 2;
    private int groupId_;

    /**
     * <code>int32 group_id = 2;</code>
     *
     * @return The groupId.
     */
    public int getGroupId() {
        return groupId_;
    }

    public static final int PROJECT_NUMBER_FIELD_NUMBER = 3;
    private int projectNumber_;

    /**
     * <code>int32 project_number = 3;</code>
     *
     * @return The projectNumber.
     */
    public int getProjectNumber() {
        return projectNumber_;
    }

    public static final int PROJECT_NAME_FIELD_NUMBER = 4;
    private volatile Object projectName_;

    /**
     * <code>string project_name = 4;</code>
     *
     * @return The projectName.
     */
    public String getProjectName() {
        Object ref = projectName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            projectName_ = s;
            return s;
        }
    }

    /**
     * <code>string project_name = 4;</code>
     *
     * @return The bytes for projectName.
     */
    public com.google.protobuf.ByteString
    getProjectNameBytes() {
        Object ref = projectName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            projectName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MEMBER_FIELD_NUMBER = 1;
    private volatile Object member_;

    /**
     * <code>string member = 1;</code>
     *
     * @return The member.
     */
    public String getMember() {
        Object ref = member_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            member_ = s;
            return s;
        }
    }

    /**
     * <code>string member = 1;</code>
     *
     * @return The bytes for member.
     */
    public com.google.protobuf.ByteString
    getMemberBytes() {
        Object ref = member_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            member_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CUSTOMER_FIELD_NUMBER = 5;
    private volatile Object customer_;

    /**
     * <code>string customer = 5;</code>
     *
     * @return The customer.
     */
    public String getCustomer() {
        Object ref = customer_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            customer_ = s;
            return s;
        }
    }

    /**
     * <code>string customer = 5;</code>
     *
     * @return The bytes for customer.
     */
    public com.google.protobuf.ByteString
    getCustomerBytes() {
        Object ref = customer_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            customer_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private volatile Object status_;

    /**
     * <code>string status = 6;</code>
     *
     * @return The status.
     */
    public String getStatus() {
        Object ref = status_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            status_ = s;
            return s;
        }
    }

    /**
     * <code>string status = 6;</code>
     *
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
    getStatusBytes() {
        Object ref = status_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            status_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int START_DATE_FIELD_NUMBER = 7;
    private volatile Object startDate_;

    /**
     * <code>string start_date = 7;</code>
     *
     * @return The startDate.
     */
    public String getStartDate() {
        Object ref = startDate_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            startDate_ = s;
            return s;
        }
    }

    /**
     * <code>string start_date = 7;</code>
     *
     * @return The bytes for startDate.
     */
    public com.google.protobuf.ByteString
    getStartDateBytes() {
        Object ref = startDate_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            startDate_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int END_DATE_FIELD_NUMBER = 8;
    private volatile Object endDate_;

    /**
     * <code>string end_date = 8;</code>
     *
     * @return The endDate.
     */
    public String getEndDate() {
        Object ref = endDate_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            endDate_ = s;
            return s;
        }
    }

    /**
     * <code>string end_date = 8;</code>
     *
     * @return The bytes for endDate.
     */
    public com.google.protobuf.ByteString
    getEndDateBytes() {
        Object ref = endDate_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            endDate_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int VERSION_FIELD_NUMBER = 9;
    private int version_;

    /**
     * <code>int32 version = 9;</code>
     *
     * @return The version.
     */
    public int getVersion() {
        return version_;
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getMemberBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, member_);
        }
        if (groupId_ != 0) {
            output.writeInt32(2, groupId_);
        }
        if (projectNumber_ != 0) {
            output.writeInt32(3, projectNumber_);
        }
        if (!getProjectNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, projectName_);
        }
        if (!getCustomerBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, customer_);
        }
        if (!getStatusBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, status_);
        }
        if (!getStartDateBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, startDate_);
        }
        if (!getEndDateBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 8, endDate_);
        }
        if (version_ != 0) {
            output.writeInt32(9, version_);
        }
        if (id_ != 0) {
            output.writeInt32(10, id_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getMemberBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, member_);
        }
        if (groupId_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, groupId_);
        }
        if (projectNumber_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, projectNumber_);
        }
        if (!getProjectNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, projectName_);
        }
        if (!getCustomerBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, customer_);
        }
        if (!getStatusBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, status_);
        }
        if (!getStartDateBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, startDate_);
        }
        if (!getEndDateBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, endDate_);
        }
        if (version_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(9, version_);
        }
        if (id_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(10, id_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Project)) {
            return super.equals(obj);
        }
        Project other = (Project) obj;

        if (getId()
                != other.getId()) return false;
        if (getGroupId()
                != other.getGroupId()) return false;
        if (getProjectNumber()
                != other.getProjectNumber()) return false;
        if (!getProjectName()
                .equals(other.getProjectName())) return false;
        if (!getMember()
                .equals(other.getMember())) return false;
        if (!getCustomer()
                .equals(other.getCustomer())) return false;
        if (!getStatus()
                .equals(other.getStatus())) return false;
        if (!getStartDate()
                .equals(other.getStartDate())) return false;
        if (!getEndDate()
                .equals(other.getEndDate())) return false;
        if (getVersion()
                != other.getVersion()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
        hash = (53 * hash) + getGroupId();
        hash = (37 * hash) + PROJECT_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getProjectNumber();
        hash = (37 * hash) + PROJECT_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getProjectName().hashCode();
        hash = (37 * hash) + MEMBER_FIELD_NUMBER;
        hash = (53 * hash) + getMember().hashCode();
        hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomer().hashCode();
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
        hash = (37 * hash) + START_DATE_FIELD_NUMBER;
        hash = (53 * hash) + getStartDate().hashCode();
        hash = (37 * hash) + END_DATE_FIELD_NUMBER;
        hash = (53 * hash) + getEndDate().hashCode();
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Project parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Project parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Project parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Project parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Project parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Project parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Project parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Project parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Project parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Project parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Project parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Project parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Project prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * </pre>
     * <p>
     * Protobuf type {@code routeguide.Project}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:routeguide.Project)
            ProjectOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MyProto.internal_static_routeguide_Project_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MyProto.internal_static_routeguide_Project_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Project.class, Builder.class);
        }

        // Construct using generatedclass.Project.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            id_ = 0;

            groupId_ = 0;

            projectNumber_ = 0;

            projectName_ = "";

            member_ = "";

            customer_ = "";

            status_ = "";

            startDate_ = "";

            endDate_ = "";

            version_ = 0;

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return MyProto.internal_static_routeguide_Project_descriptor;
        }

        @Override
        public Project getDefaultInstanceForType() {
            return Project.getDefaultInstance();
        }

        @Override
        public Project build() {
            Project result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public Project buildPartial() {
            Project result = new Project(this);
            result.id_ = id_;
            result.groupId_ = groupId_;
            result.projectNumber_ = projectNumber_;
            result.projectName_ = projectName_;
            result.member_ = member_;
            result.customer_ = customer_;
            result.status_ = status_;
            result.startDate_ = startDate_;
            result.endDate_ = endDate_;
            result.version_ = version_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Project) {
                return mergeFrom((Project) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Project other) {
            if (other == Project.getDefaultInstance()) return this;
            if (other.getId() != 0) {
                setId(other.getId());
            }
            if (other.getGroupId() != 0) {
                setGroupId(other.getGroupId());
            }
            if (other.getProjectNumber() != 0) {
                setProjectNumber(other.getProjectNumber());
            }
            if (!other.getProjectName().isEmpty()) {
                projectName_ = other.projectName_;
                onChanged();
            }
            if (!other.getMember().isEmpty()) {
                member_ = other.member_;
                onChanged();
            }
            if (!other.getCustomer().isEmpty()) {
                customer_ = other.customer_;
                onChanged();
            }
            if (!other.getStatus().isEmpty()) {
                status_ = other.status_;
                onChanged();
            }
            if (!other.getStartDate().isEmpty()) {
                startDate_ = other.startDate_;
                onChanged();
            }
            if (!other.getEndDate().isEmpty()) {
                endDate_ = other.endDate_;
                onChanged();
            }
            if (other.getVersion() != 0) {
                setVersion(other.getVersion());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Project parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Project) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int id_;

        /**
         * <code>int32 id = 10;</code>
         *
         * @return The id.
         */
        public int getId() {
            return id_;
        }

        /**
         * <code>int32 id = 10;</code>
         *
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(int value) {

            id_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 id = 10;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearId() {

            id_ = 0;
            onChanged();
            return this;
        }

        private int groupId_;

        /**
         * <code>int32 group_id = 2;</code>
         *
         * @return The groupId.
         */
        public int getGroupId() {
            return groupId_;
        }

        /**
         * <code>int32 group_id = 2;</code>
         *
         * @param value The groupId to set.
         * @return This builder for chaining.
         */
        public Builder setGroupId(int value) {

            groupId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 group_id = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearGroupId() {

            groupId_ = 0;
            onChanged();
            return this;
        }

        private int projectNumber_;

        /**
         * <code>int32 project_number = 3;</code>
         *
         * @return The projectNumber.
         */
        public int getProjectNumber() {
            return projectNumber_;
        }

        /**
         * <code>int32 project_number = 3;</code>
         *
         * @param value The projectNumber to set.
         * @return This builder for chaining.
         */
        public Builder setProjectNumber(int value) {

            projectNumber_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 project_number = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearProjectNumber() {

            projectNumber_ = 0;
            onChanged();
            return this;
        }

        private Object projectName_ = "";

        /**
         * <code>string project_name = 4;</code>
         *
         * @return The projectName.
         */
        public String getProjectName() {
            Object ref = projectName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                projectName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string project_name = 4;</code>
         *
         * @return The bytes for projectName.
         */
        public com.google.protobuf.ByteString
        getProjectNameBytes() {
            Object ref = projectName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                projectName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string project_name = 4;</code>
         *
         * @param value The projectName to set.
         * @return This builder for chaining.
         */
        public Builder setProjectName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            projectName_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string project_name = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearProjectName() {

            projectName_ = getDefaultInstance().getProjectName();
            onChanged();
            return this;
        }

        /**
         * <code>string project_name = 4;</code>
         *
         * @param value The bytes for projectName to set.
         * @return This builder for chaining.
         */
        public Builder setProjectNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            projectName_ = value;
            onChanged();
            return this;
        }

        private Object member_ = "";

        /**
         * <code>string member = 1;</code>
         *
         * @return The member.
         */
        public String getMember() {
            Object ref = member_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                member_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string member = 1;</code>
         *
         * @return The bytes for member.
         */
        public com.google.protobuf.ByteString
        getMemberBytes() {
            Object ref = member_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                member_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string member = 1;</code>
         *
         * @param value The member to set.
         * @return This builder for chaining.
         */
        public Builder setMember(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            member_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string member = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMember() {

            member_ = getDefaultInstance().getMember();
            onChanged();
            return this;
        }

        /**
         * <code>string member = 1;</code>
         *
         * @param value The bytes for member to set.
         * @return This builder for chaining.
         */
        public Builder setMemberBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            member_ = value;
            onChanged();
            return this;
        }

        private Object customer_ = "";

        /**
         * <code>string customer = 5;</code>
         *
         * @return The customer.
         */
        public String getCustomer() {
            Object ref = customer_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                customer_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string customer = 5;</code>
         *
         * @return The bytes for customer.
         */
        public com.google.protobuf.ByteString
        getCustomerBytes() {
            Object ref = customer_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                customer_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string customer = 5;</code>
         *
         * @param value The customer to set.
         * @return This builder for chaining.
         */
        public Builder setCustomer(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            customer_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string customer = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCustomer() {

            customer_ = getDefaultInstance().getCustomer();
            onChanged();
            return this;
        }

        /**
         * <code>string customer = 5;</code>
         *
         * @param value The bytes for customer to set.
         * @return This builder for chaining.
         */
        public Builder setCustomerBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            customer_ = value;
            onChanged();
            return this;
        }

        private Object status_ = "";

        /**
         * <code>string status = 6;</code>
         *
         * @return The status.
         */
        public String getStatus() {
            Object ref = status_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                status_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string status = 6;</code>
         *
         * @return The bytes for status.
         */
        public com.google.protobuf.ByteString
        getStatusBytes() {
            Object ref = status_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                status_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string status = 6;</code>
         *
         * @param value The status to set.
         * @return This builder for chaining.
         */
        public Builder setStatus(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            status_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string status = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStatus() {

            status_ = getDefaultInstance().getStatus();
            onChanged();
            return this;
        }

        /**
         * <code>string status = 6;</code>
         *
         * @param value The bytes for status to set.
         * @return This builder for chaining.
         */
        public Builder setStatusBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            status_ = value;
            onChanged();
            return this;
        }

        private Object startDate_ = "";

        /**
         * <code>string start_date = 7;</code>
         *
         * @return The startDate.
         */
        public String getStartDate() {
            Object ref = startDate_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                startDate_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string start_date = 7;</code>
         *
         * @return The bytes for startDate.
         */
        public com.google.protobuf.ByteString
        getStartDateBytes() {
            Object ref = startDate_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                startDate_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string start_date = 7;</code>
         *
         * @param value The startDate to set.
         * @return This builder for chaining.
         */
        public Builder setStartDate(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            startDate_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string start_date = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStartDate() {

            startDate_ = getDefaultInstance().getStartDate();
            onChanged();
            return this;
        }

        /**
         * <code>string start_date = 7;</code>
         *
         * @param value The bytes for startDate to set.
         * @return This builder for chaining.
         */
        public Builder setStartDateBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            startDate_ = value;
            onChanged();
            return this;
        }

        private Object endDate_ = "";

        /**
         * <code>string end_date = 8;</code>
         *
         * @return The endDate.
         */
        public String getEndDate() {
            Object ref = endDate_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                endDate_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string end_date = 8;</code>
         *
         * @return The bytes for endDate.
         */
        public com.google.protobuf.ByteString
        getEndDateBytes() {
            Object ref = endDate_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                endDate_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string end_date = 8;</code>
         *
         * @param value The endDate to set.
         * @return This builder for chaining.
         */
        public Builder setEndDate(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            endDate_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string end_date = 8;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearEndDate() {

            endDate_ = getDefaultInstance().getEndDate();
            onChanged();
            return this;
        }

        /**
         * <code>string end_date = 8;</code>
         *
         * @param value The bytes for endDate to set.
         * @return This builder for chaining.
         */
        public Builder setEndDateBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            endDate_ = value;
            onChanged();
            return this;
        }

        private int version_;

        /**
         * <code>int32 version = 9;</code>
         *
         * @return The version.
         */
        public int getVersion() {
            return version_;
        }

        /**
         * <code>int32 version = 9;</code>
         *
         * @param value The version to set.
         * @return This builder for chaining.
         */
        public Builder setVersion(int value) {

            version_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 version = 9;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearVersion() {

            version_ = 0;
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:routeguide.Project)
    }

    // @@protoc_insertion_point(class_scope:routeguide.Project)
    private static final Project DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new Project();
    }

    public static Project getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Project>
            PARSER = new com.google.protobuf.AbstractParser<Project>() {
        @Override
        public Project parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Project(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Project> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Project> getParserForType() {
        return PARSER;
    }

    @Override
    public Project getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

