// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Project.proto

package SpringBoot.dto;

/**
 * Protobuf type {@code routeguide.Request}
 */
public final class Request extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:routeguide.Request)
        RequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Request() {
        search_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new Request();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private Request(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 8: {

                        typeRequest_ = input.readInt32();
                        break;
                    }
                    case 16: {

                        page_ = input.readInt32();
                        break;
                    }
                    case 24: {

                        maxItemInPage_ = input.readInt32();
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        search_ = s;
                        break;
                    }
                    case 42: {
                        Project.Builder subBuilder = null;
                        if (project_ != null) {
                            subBuilder = project_.toBuilder();
                        }
                        project_ = input.readMessage(Project.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(project_);
                            project_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return MyProto.internal_static_routeguide_Request_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return MyProto.internal_static_routeguide_Request_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Request.class, Builder.class);
    }

    public static final int TYPE_REQUEST_FIELD_NUMBER = 1;
    private int typeRequest_;

    /**
     * <code>int32 type_request = 1;</code>
     *
     * @return The typeRequest.
     */
    public int getTypeRequest() {
        return typeRequest_;
    }

    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;

    /**
     * <code>int32 page = 2;</code>
     *
     * @return The page.
     */
    public int getPage() {
        return page_;
    }

    public static final int MAX_ITEM_IN_PAGE_FIELD_NUMBER = 3;
    private int maxItemInPage_;

    /**
     * <code>int32 max_item_in_page = 3;</code>
     *
     * @return The maxItemInPage.
     */
    public int getMaxItemInPage() {
        return maxItemInPage_;
    }

    public static final int SEARCH_FIELD_NUMBER = 4;
    private volatile Object search_;

    /**
     * <code>string search = 4;</code>
     *
     * @return The search.
     */
    public String getSearch() {
        Object ref = search_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            search_ = s;
            return s;
        }
    }

    /**
     * <code>string search = 4;</code>
     *
     * @return The bytes for search.
     */
    public com.google.protobuf.ByteString
    getSearchBytes() {
        Object ref = search_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            search_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PROJECT_FIELD_NUMBER = 5;
    private Project project_;

    /**
     * <code>.routeguide.Project project = 5;</code>
     *
     * @return Whether the project field is set.
     */
    public boolean hasProject() {
        return project_ != null;
    }

    /**
     * <code>.routeguide.Project project = 5;</code>
     *
     * @return The project.
     */
    public Project getProject() {
        return project_ == null ? Project.getDefaultInstance() : project_;
    }

    /**
     * <code>.routeguide.Project project = 5;</code>
     */
    public ProjectOrBuilder getProjectOrBuilder() {
        return getProject();
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (typeRequest_ != 0) {
            output.writeInt32(1, typeRequest_);
        }
        if (page_ != 0) {
            output.writeInt32(2, page_);
        }
        if (maxItemInPage_ != 0) {
            output.writeInt32(3, maxItemInPage_);
        }
        if (!getSearchBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, search_);
        }
        if (project_ != null) {
            output.writeMessage(5, getProject());
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (typeRequest_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, typeRequest_);
        }
        if (page_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, page_);
        }
        if (maxItemInPage_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(3, maxItemInPage_);
        }
        if (!getSearchBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, search_);
        }
        if (project_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, getProject());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Request)) {
            return super.equals(obj);
        }
        Request other = (Request) obj;

        if (getTypeRequest()
                != other.getTypeRequest()) return false;
        if (getPage()
                != other.getPage()) return false;
        if (getMaxItemInPage()
                != other.getMaxItemInPage()) return false;
        if (!getSearch()
                .equals(other.getSearch())) return false;
        if (hasProject() != other.hasProject()) return false;
        if (hasProject()) {
            if (!getProject()
                    .equals(other.getProject())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TYPE_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getTypeRequest();
        hash = (37 * hash) + PAGE_FIELD_NUMBER;
        hash = (53 * hash) + getPage();
        hash = (37 * hash) + MAX_ITEM_IN_PAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMaxItemInPage();
        hash = (37 * hash) + SEARCH_FIELD_NUMBER;
        hash = (53 * hash) + getSearch().hashCode();
        if (hasProject()) {
            hash = (37 * hash) + PROJECT_FIELD_NUMBER;
            hash = (53 * hash) + getProject().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Request parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Request parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Request parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Request parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Request parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Request parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Request parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Request parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Request parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Request parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Request parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Request parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Request prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code routeguide.Request}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:routeguide.Request)
            RequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MyProto.internal_static_routeguide_Request_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MyProto.internal_static_routeguide_Request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Request.class, Builder.class);
        }

        // Construct using generatedclass.Request.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            typeRequest_ = 0;

            page_ = 0;

            maxItemInPage_ = 0;

            search_ = "";

            if (projectBuilder_ == null) {
                project_ = null;
            } else {
                project_ = null;
                projectBuilder_ = null;
            }
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return MyProto.internal_static_routeguide_Request_descriptor;
        }

        @Override
        public Request getDefaultInstanceForType() {
            return Request.getDefaultInstance();
        }

        @Override
        public Request build() {
            Request result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public Request buildPartial() {
            Request result = new Request(this);
            result.typeRequest_ = typeRequest_;
            result.page_ = page_;
            result.maxItemInPage_ = maxItemInPage_;
            result.search_ = search_;
            if (projectBuilder_ == null) {
                result.project_ = project_;
            } else {
                result.project_ = projectBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Request) {
                return mergeFrom((Request) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Request other) {
            if (other == Request.getDefaultInstance()) return this;
            if (other.getTypeRequest() != 0) {
                setTypeRequest(other.getTypeRequest());
            }
            if (other.getPage() != 0) {
                setPage(other.getPage());
            }
            if (other.getMaxItemInPage() != 0) {
                setMaxItemInPage(other.getMaxItemInPage());
            }
            if (!other.getSearch().isEmpty()) {
                search_ = other.search_;
                onChanged();
            }
            if (other.hasProject()) {
                mergeProject(other.getProject());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Request parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Request) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int typeRequest_;

        /**
         * <code>int32 type_request = 1;</code>
         *
         * @return The typeRequest.
         */
        public int getTypeRequest() {
            return typeRequest_;
        }

        /**
         * <code>int32 type_request = 1;</code>
         *
         * @param value The typeRequest to set.
         * @return This builder for chaining.
         */
        public Builder setTypeRequest(int value) {

            typeRequest_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 type_request = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearTypeRequest() {

            typeRequest_ = 0;
            onChanged();
            return this;
        }

        private int page_;

        /**
         * <code>int32 page = 2;</code>
         *
         * @return The page.
         */
        public int getPage() {
            return page_;
        }

        /**
         * <code>int32 page = 2;</code>
         *
         * @param value The page to set.
         * @return This builder for chaining.
         */
        public Builder setPage(int value) {

            page_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 page = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPage() {

            page_ = 0;
            onChanged();
            return this;
        }

        private int maxItemInPage_;

        /**
         * <code>int32 max_item_in_page = 3;</code>
         *
         * @return The maxItemInPage.
         */
        public int getMaxItemInPage() {
            return maxItemInPage_;
        }

        /**
         * <code>int32 max_item_in_page = 3;</code>
         *
         * @param value The maxItemInPage to set.
         * @return This builder for chaining.
         */
        public Builder setMaxItemInPage(int value) {

            maxItemInPage_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 max_item_in_page = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMaxItemInPage() {

            maxItemInPage_ = 0;
            onChanged();
            return this;
        }

        private Object search_ = "";

        /**
         * <code>string search = 4;</code>
         *
         * @return The search.
         */
        public String getSearch() {
            Object ref = search_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                search_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string search = 4;</code>
         *
         * @return The bytes for search.
         */
        public com.google.protobuf.ByteString
        getSearchBytes() {
            Object ref = search_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                search_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string search = 4;</code>
         *
         * @param value The search to set.
         * @return This builder for chaining.
         */
        public Builder setSearch(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            search_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string search = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSearch() {

            search_ = getDefaultInstance().getSearch();
            onChanged();
            return this;
        }

        /**
         * <code>string search = 4;</code>
         *
         * @param value The bytes for search to set.
         * @return This builder for chaining.
         */
        public Builder setSearchBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            search_ = value;
            onChanged();
            return this;
        }

        private Project project_;
        private com.google.protobuf.SingleFieldBuilderV3<
                Project, Project.Builder, ProjectOrBuilder> projectBuilder_;

        /**
         * <code>.routeguide.Project project = 5;</code>
         *
         * @return Whether the project field is set.
         */
        public boolean hasProject() {
            return projectBuilder_ != null || project_ != null;
        }

        /**
         * <code>.routeguide.Project project = 5;</code>
         *
         * @return The project.
         */
        public Project getProject() {
            if (projectBuilder_ == null) {
                return project_ == null ? Project.getDefaultInstance() : project_;
            } else {
                return projectBuilder_.getMessage();
            }
        }

        /**
         * <code>.routeguide.Project project = 5;</code>
         */
        public Builder setProject(Project value) {
            if (projectBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                project_ = value;
                onChanged();
            } else {
                projectBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.routeguide.Project project = 5;</code>
         */
        public Builder setProject(
                Project.Builder builderForValue) {
            if (projectBuilder_ == null) {
                project_ = builderForValue.build();
                onChanged();
            } else {
                projectBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.routeguide.Project project = 5;</code>
         */
        public Builder mergeProject(Project value) {
            if (projectBuilder_ == null) {
                if (project_ != null) {
                    project_ =
                            Project.newBuilder(project_).mergeFrom(value).buildPartial();
                } else {
                    project_ = value;
                }
                onChanged();
            } else {
                projectBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.routeguide.Project project = 5;</code>
         */
        public Builder clearProject() {
            if (projectBuilder_ == null) {
                project_ = null;
                onChanged();
            } else {
                project_ = null;
                projectBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.routeguide.Project project = 5;</code>
         */
        public Project.Builder getProjectBuilder() {

            onChanged();
            return getProjectFieldBuilder().getBuilder();
        }

        /**
         * <code>.routeguide.Project project = 5;</code>
         */
        public ProjectOrBuilder getProjectOrBuilder() {
            if (projectBuilder_ != null) {
                return projectBuilder_.getMessageOrBuilder();
            } else {
                return project_ == null ?
                        Project.getDefaultInstance() : project_;
            }
        }

        /**
         * <code>.routeguide.Project project = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Project, Project.Builder, ProjectOrBuilder>
        getProjectFieldBuilder() {
            if (projectBuilder_ == null) {
                projectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Project, Project.Builder, ProjectOrBuilder>(
                        getProject(),
                        getParentForChildren(),
                        isClean());
                project_ = null;
            }
            return projectBuilder_;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:routeguide.Request)
    }

    // @@protoc_insertion_point(class_scope:routeguide.Request)
    private static final Request DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new Request();
    }

    public static Request getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
            PARSER = new com.google.protobuf.AbstractParser<Request>() {
        @Override
        public Request parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Request(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Request> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
        return PARSER;
    }

    @Override
    public Request getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

