// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Project.proto

package SpringBoot.dto;

public interface ResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:routeguide.Response)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 is_success = 1;</code>
     *
     * @return The isSuccess.
     */
    int getIsSuccess();

    /**
     * <code>string message = 2;</code>
     *
     * @return The message.
     */
    String getMessage();

    /**
     * <code>string message = 2;</code>
     *
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
    getMessageBytes();
}
